name: call-reusable-workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build:
    uses: joshjohanning-org/contexts-testing/.github/workflows/contexts.yml@main
    secrets: inherit
    
